services:
- type: web
  name: wordpress-woo-makr
  env: docker
  disk:
    name: wordpress-woo-makr
    mountPath: /var/www/html
  envVars:
  - from-group: word-settings
  - from-group: in_oregon
  - key: WORDPRESS_TABLE_PREFIX
    value: WP_WM_
    
- type: web
  name: wordpress-neoai-health
  env: docker
  region: frankfurt
  disk:
    name: wordpress-neoai-health
    mountPath: /var/www/html
  envVars:
  - from-group: word-settings
  - from-group: in_eu
  - key: WORDPRESS_TABLE_PREFIX
    value: WP_NE_

- type: web
  name: wordpress-neoai-one
  env: docker
  disk:
    name: wordpress-neoai-one
    mountPath: /var/www/html
  envVars:
  - from-group: word-settings
  - from-group: in_oregon
  - key: WORDPRESS_TABLE_PREFIX
    value: WP_NO_
  
- type: pserv
  name: mysql-wordpress-oregon
  repo: https://github.com/render-examples/mysql.git
  env: docker
  disk:
    name: mysql-wordpress-oregon
    mountPath: /var/lib/mysql
  envVars:
    - from-group: word_settings
    - key: MYSQL_ROOT_PASSWORD
      generateValue: true

- type: pserv
  name: mysql-wordpress-eu
  repo: https://github.com/render-examples/mysql.git
  env: docker
  region: frankfurt
  disk:
    name: mysql-wordpress-eu
    mountPath: /var/lib/mysql
  envVars:
    - from-group: word_settings
    - key: MYSQL_ROOT_PASSWORD
      generateValue: true

envVarGroups:
  - name: word-settings
    envVars:
    - key: MYSQL_DATABASE
      value: mysql
    - key: MYSQL_USER
      value: mysql
    - key: MYSQL_PASSWORD
      generateValue: true
    
  - name: in_oregon
    envVars:
    - key: WORDPRESS_DB_HOST
      value: mysql-wordpress-oregon
      
  - name: in_eu
    envVars:
    - key: WORDPRESS_DB_HOST
      value: mysql-wordpress-eu  
